### ISSUE TITLE
Hébergement

### ISSUE THREAD

**Issue by sangmin-shim** [epsi-mspr-bloc-4-g4/livrables#9]

**Comment by jul-fls** [comment]
Le déploiement est fait via une stack docker compose globale au 4 micro services : 
- Api Gateway
- Api Clients
- Api Commandes
- Api Produits

Il n'y as donc pas lieu d'y avoir une stack docker compose par micro service étant donné qu'il s'agit d'un déploiement global et unifié.
Le docker compose est créé et en place.
